In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('salaries.csv')
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [3]:
# X(independent variable)
inputs = df.drop('salary_more_then_100k', axis=1)
inputs

       company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [4]:
# y(dependent variable)
target = df['salary_more_then_100k']
target.head()

0    0
1    0
2    1
3    1
4    0
Name: salary_more_then_100k, dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
ohe = LabelEncoder()

In [7]:
inputs['company_n'] = ohe.fit_transform(inputs['company'])
inputs['job_n'] = ohe.fit_transform(inputs['job'])
inputs['degree_n'] = ohe.fit_transform(inputs['degree'])

In [9]:
inputs.head()

  company                  job     degree  company_n  job_n  degree_n
0  google      sales executive  bachelors          2      2         0
1  google      sales executive    masters          2      2         1
2  google     business manager  bachelors          2      0         0
3  google     business manager    masters          2      0         1
4  google  computer programmer  bachelors          2      1         0

In [10]:
inputs_n = inputs.drop(['company', 'job', 'degree'], axis=1)
inputs_n

    company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [14]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
model = DecisionTreeClassifier()

In [17]:
model.fit(inputs_n, target)

DecisionTreeClassifier()

In [21]:
a = df.drop(['company', 'job', 'degree'], axis=1)
a.head()

   salary_more_then_100k
0                      0
1                      0
2                      1
3                      1
4                      0

In [45]:
frames = [inputs_n, a]
b = pd.concat(frames, axis=1)
b

    company_n  job_n  degree_n  salary_more_then_100k
0           2      2         0                      0
1           2      2         1                      0
2           2      0         0                      1
3           2      0         1                      1
4           2      1         0                      0
5           2      1         1                      1
6           0      2         1                      0
7           0      1         0                      0
8           0      0         0                      0
9           0      0         1                      1
10          1      2         0                      1
11          1      2         1                      1
12          1      0         0                      1
13          1      0         1                      1
14          1      1         0                      1
15          1      1         1                      1

In [37]:
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(b[['company_n', 'job_n', 'degree_n']], b.salary_more_then_100k, test_size=0.1)

In [41]:
X_train

    company_n  job_n  degree_n
4           2      1         0
1           2      2         1
8           0      0         0
13          1      0         1
15          1      1         1
3           2      0         1
2           2      0         0
10          1      2         0
0           2      2         0
12          1      0         0
14          1      1         0
9           0      0         1
5           2      1         1
11          1      2         1

In [42]:
X_test

   company_n  job_n  degree_n
6          0      2         1
7          0      1         0

In [43]:
y_train

4     0
1     0
8     0
13    1
15    1
3     1
2     1
10    1
0     0
12    1
14    1
9     1
5     1
11    1
Name: salary_more_then_100k, dtype: int64

In [44]:
y_test

6    0
7    0
Name: salary_more_then_100k, dtype: int64

In [46]:
#we have alraedy done the training using decision tree classifier, so let's predict now
model.predict(X_test)

array([0, 0], dtype=int64)

In [47]:
model.score(X_test, y_test)

1.0