# The Use of Decision Classifier Using Sklearn Digits Data

### Importing Pandas Library and Loading Digits Data

In [1]:
import pandas as pd
from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [7]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating Digit DataFrame

In [8]:
df = pd.DataFrame(digits.data, columns=digits.feature_names)
df.head()

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_6,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0

### Adding Target Column To DataFrame

In [9]:
df['target'] = digits.target
df.head()

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7,target
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4

### Importing Train Test Split from Sklearn

In [10]:
from sklearn.model_selection import train_test_split

### Splitting Data Into Training and Testing Data In Ratio 80:20

In [13]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('target', axis=1), df.target, test_size=0.2 )

### Length of Training and Testing Data

In [16]:
len(X_train)

1437

In [17]:
len(y_train)

1437

In [18]:
len(X_test)

360

In [19]:
len(y_test)

360

### Importing Support Vector Machine

In [21]:
from sklearn.svm import SVC

In [22]:
model = SVC()

### Model Training

In [23]:
model.fit(X_train, y_train)

SVC()

### Model Accuracy

In [24]:
model.score(X_test, y_test)

0.9861111111111112

### Model Testing

In [25]:
model.predict(X_test)

array([9, 6, 7, 9, 6, 1, 2, 3, 2, 4, 6, 0, 5, 4, 4, 1, 9, 3, 3, 0, 8, 0,
       6, 0, 2, 6, 2, 1, 6, 9, 0, 5, 3, 0, 8, 0, 8, 7, 8, 1, 5, 0, 2, 7,
       6, 8, 7, 0, 6, 0, 6, 3, 3, 2, 1, 7, 2, 4, 5, 5, 7, 3, 6, 0, 6, 2,
       1, 2, 5, 0, 5, 5, 7, 9, 5, 7, 1, 8, 8, 4, 3, 5, 3, 7, 0, 0, 4, 0,
       9, 9, 4, 3, 1, 6, 9, 1, 8, 7, 3, 0, 5, 4, 1, 5, 2, 6, 6, 4, 1, 0,
       0, 4, 2, 0, 7, 5, 6, 5, 1, 6, 2, 2, 6, 5, 2, 3, 7, 7, 4, 9, 5, 8,
       6, 4, 6, 6, 0, 0, 7, 1, 8, 1, 8, 8, 5, 7, 6, 9, 4, 9, 2, 6, 0, 0,
       0, 6, 4, 1, 6, 3, 3, 2, 3, 7, 4, 0, 1, 2, 7, 3, 5, 4, 8, 9, 9, 1,
       8, 7, 2, 8, 2, 2, 0, 6, 0, 7, 0, 8, 4, 5, 4, 4, 3, 1, 1, 8, 6, 4,
       5, 1, 4, 2, 6, 9, 5, 9, 4, 9, 0, 3, 2, 5, 8, 2, 9, 6, 8, 3, 8, 1,
       9, 2, 1, 4, 4, 0, 2, 3, 1, 2, 4, 2, 0, 2, 3, 5, 3, 3, 4, 4, 4, 1,
       5, 3, 9, 5, 8, 7, 5, 1, 5, 8, 2, 1, 4, 5, 9, 9, 0, 4, 2, 2, 9, 7,
       4, 8, 5, 2, 8, 7, 8, 1, 3, 9, 9, 7, 7, 3, 6, 9, 2, 6, 2, 6, 4, 6,
       4, 2, 5, 2, 0, 7, 1, 7, 1, 3, 8, 7, 0, 9, 0, 9, 5, 2, 7, 8, 7, 2,
       4, 8, 6, 8, 4, 6, 9, 9, 1, 4, 7, 0, 3, 8, 7, 4, 0, 1, 4, 1, 3, 5,
       9, 1, 8, 2, 9, 2, 2, 7, 3, 9, 2, 5, 3, 4, 8, 9, 6, 2, 9, 7, 6, 3,
       6, 6, 7, 0, 2, 4, 5, 0])