In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [3]:
df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis=1)

     Pclass     Sex   Age     Fare  Survived
0         3    male  22.0   7.2500         0
1         1  female  38.0  71.2833         1
2         3  female  26.0   7.9250         1
3         1  female  35.0  53.1000         1
4         3    male  35.0   8.0500         0
..      ...     ...   ...      ...       ...
886       2    male  27.0  13.0000         0
887       1  female  19.0  30.0000         1
888       3  female   NaN  23.4500         0
889       1    male  26.0  30.0000         1
890       3    male  32.0   7.7500         0

[891 rows x 5 columns]

In [4]:
X = df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked', 'Survived'], axis=1)

In [5]:
y = df.Survived

In [6]:
dummies = pd.get_dummies(df.Sex)
dummies.head()

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [7]:
X = pd.concat([X, dummies], axis=1)
X

     Pclass     Sex   Age     Fare  female  male
0         3    male  22.0   7.2500       0     1
1         1  female  38.0  71.2833       1     0
2         3  female  26.0   7.9250       1     0
3         1  female  35.0  53.1000       1     0
4         3    male  35.0   8.0500       0     1
..      ...     ...   ...      ...     ...   ...
886       2    male  27.0  13.0000       0     1
887       1  female  19.0  30.0000       1     0
888       3  female   NaN  23.4500       1     0
889       1    male  26.0  30.0000       0     1
890       3    male  32.0   7.7500       0     1

[891 rows x 6 columns]

In [8]:
X.drop('Sex', axis=1, inplace=True)
X.head()

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [18]:
X.columns[X.isna().any()]

Index(['Age'], dtype='object')

In [17]:
##the above means that some of the Age values is NaN

In [19]:
X.Age = X.Age.fillna(X.Age.mean())
X

     Pclass        Age     Fare  female  male
0         3  22.000000   7.2500       0     1
1         1  38.000000  71.2833       1     0
2         3  26.000000   7.9250       1     0
3         1  35.000000  53.1000       1     0
4         3  35.000000   8.0500       0     1
..      ...        ...      ...     ...   ...
886       2  27.000000  13.0000       0     1
887       1  19.000000  30.0000       1     0
888       3  29.699118  23.4500       1     0
889       1  26.000000  30.0000       0     1
890       3  32.000000   7.7500       0     1

[891 rows x 5 columns]

In [20]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [26]:
from sklearn.naive_bayes import GaussianNB

In [28]:
model = GaussianNB()

In [29]:
model.fit(X_train, y_train)

GaussianNB()

In [30]:
model.score(X_test, y_test)

0.7877094972067039

In [32]:
X_test.head(10)

     Pclass        Age     Fare  female  male
664       3  20.000000   7.9250       0     1
849       1  29.699118  89.1042       1     0
552       3  29.699118   7.8292       0     1
277       2  29.699118   0.0000       0     1
511       3  29.699118   8.0500       0     1
403       3  28.000000  15.8500       0     1
857       1  51.000000  26.5500       0     1
32        3  29.699118   7.7500       1     0
194       1  44.000000  27.7208       1     0
695       2  52.000000  13.5000       0     1

In [33]:
y_test.head(10)

664    1
849    1
552    0
277    0
511    0
403    0
857    1
32     1
194    1
695    0
Name: Survived, dtype: int64

In [34]:
model.predict(X_test.head(10))

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int64)

In [36]:
model.predict_proba(X_test.head(10))

array([[0.98783687, 0.01216313],
       [0.00125692, 0.99874308],
       [0.98976098, 0.01023902],
       [0.97613002, 0.02386998],
       [0.98977442, 0.01022558],
       [0.98977871, 0.01022129],
       [0.92494117, 0.07505883],
       [0.0695992 , 0.9304008 ],
       [0.01005008, 0.98994992],
       [0.97723002, 0.02276998]])