### Importing Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

### Loading csv file

In [2]:
df = pd.read_csv('homeprices.csv')
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

## Data Cleaning
### Handling missing value(s)

In [5]:
import math
bedroom_median = df.bedrooms.median()
bedroom_median

4.0

In [6]:
df.bedrooms.fillna(bedroom_median)

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [16]:
##saving changes to file

In [7]:
df.bedrooms = df.bedrooms.fillna(bedroom_median)
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

### Model Training

In [8]:
reg = linear_model.LinearRegression()

In [17]:
reg.fit(df[['area','bedrooms','age']], df.price)
## the independent variables are fitted in the square brackets

LinearRegression()

### Model Testing

In [11]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [12]:
reg.intercept_

221323.00186540425

In [13]:
reg.predict([[3000,3,40]])

C:\Users\CHUFESS\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([498408.25158031])

In [14]:
# This is how the value was obtained: y = m1*x1 + m2*x2 + m3*x3 + b