In [1]:
import numpy as py
import pandas as pd
from sklearn import linear_model

In [17]:
raw_data = pd.read_csv('hiring.csv')
raw_data

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [19]:
raw_data.rename(columns={'test_score(out of 10)':'test_score_Out_of_10',
                         'interview_score(out of 10)':'interview_score_Out_of_10', 
                         'salary($)':'salary_USD'}, inplace=True)
raw_data

  experience  test_score_Out_of_10  interview_score_Out_of_10  salary_USD
0        NaN                   8.0                          9       50000
1        NaN                   8.0                          6       45000
2       five                   6.0                          7       60000
3        two                  10.0                         10       65000
4      seven                   9.0                          6       70000
5      three                   7.0                         10       62000
6        ten                   NaN                          7       72000
7     eleven                   7.0                          8       80000

In [20]:
test_score_median = raw_data.test_score_Out_of_10.median()
test_score_median

8.0

In [21]:
new_data_set = raw_data.fillna({'test_score_Out_of_10':8 , 'experience':'zero'})
new_data_set

  experience  test_score_Out_of_10  interview_score_Out_of_10  salary_USD
0       zero                   8.0                          9       50000
1       zero                   8.0                          6       45000
2       five                   6.0                          7       60000
3        two                  10.0                         10       65000
4      seven                   9.0                          6       70000
5      three                   7.0                         10       62000
6        ten                   8.0                          7       72000
7     eleven                   7.0                          8       80000

In [25]:
pip install word2number

Requirement already satisfied: word2number in c:\users\chufess\anaconda3\lib\site-packages (1.1)
Note: you may need to restart the kernel to use updated packages.

In [26]:
from word2number import w2n

In [29]:
new_data_set['experience'] = new_data_set.experience.astype(str)
new_data_set['experience'] = new_data_set['experience'].fillna('zero')
new_data_set.experience = new_data_set.experience.apply(w2n.word_to_num)
new_data_set

   experience  test_score_Out_of_10  interview_score_Out_of_10  salary_USD
0           0                   8.0                          9       50000
1           0                   8.0                          6       45000
2           5                   6.0                          7       60000
3           2                  10.0                         10       65000
4           7                   9.0                          6       70000
5           3                   7.0                         10       62000
6          10                   8.0                          7       72000
7          11                   7.0                          8       80000

In [31]:
reg = linear_model.LinearRegression()

In [32]:
reg.fit(new_data_set[['experience', 'test_score_Out_of_10', 'interview_score_Out_of_10']], new_data_set.salary_USD)

LinearRegression()

In [34]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [35]:
reg.intercept_

17737.26346433768

In [36]:
reg.predict([[2,9,6]])

C:\Users\CHUFESS\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53205.96797671])

In [37]:
reg.predict([[12,10,10]])

C:\Users\CHUFESS\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([92002.18340611])